name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: roota
          MYSQL_ROOT_PASSWORD: aloha
          MYSQL_DATABASE: usersdb
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm install
    - name: Start MySQL
      run: sudo /etc/init.d/mysql start
    - name: Install cliente mysql
      run: sudo apt-get install mysql-client
    - name: Liberar acesso
      run: sudo -i
    - name: Criar tabelas
      run: mysql -h localhost --host=localhost --user=root usersdb < estrutura.sql
    - name: Run tests
      run: npm test