name: Node.js CI

on: push
    # branches: [ main ]
  # pull_request:
    # branches: [ main ]

jobs:
  Teste:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          # MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: aloha
          MYSQL_DATABASE: usersdb
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - name: Configure MySQL permissions
      run: mysql -h127.0.0.1 --port 3306 -u root -paloha -e "ALTER USER 'root'@'%' IDENTIFIED BY 'aloha'; GRANT ALL PRIVILEGES ON *.* TO 'root'@'%'; FLUSH PRIVILEGES;"
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm install
    - name: Install cliente mysql
      run:  apt-get install mysql-client
    - name: Criar tabelas
      run: mysql -h127.0.0.1 --port 3306 -u root usersdb -paloha < estrutura.sql
    - name: Run tests
      env:
        MYSQL_USER: root
        MYSQL_PASSWORD: aloha
        MYSQL_DATABASE: usersdb
      run: npm test